// lib/core/constants/zone_data.dart
// Hardcoded geographic data for Bahrain fishing zones, MPAs, and confirmed spots.

/// Zone polygons – list of [lat, lng] points.
const Map<String, List<List<double>>> kZonePolygons = {
  'northern': [
    [26.33, 50.40],
    [26.58, 50.40],
    [26.58, 50.65],
    [26.33, 50.65],
  ],
  'eastern': [
    [25.80, 50.55],
    [26.33, 50.55],
    [26.33, 50.90],
    [25.80, 50.90],
  ],
  'western': [
    [25.75, 50.25],
    [26.33, 50.25],
    [26.33, 50.55],
    [25.75, 50.55],
  ],
};

const Map<String, String> kZoneNamesAr = {
  'northern': 'المنطقة الشمالية',
  'eastern': 'المنطقة الشرقية',
  'western': 'المنطقة الغربية',
};

/// MPA circles – center [lat, lng] + radius in km.
const List<Map<String, dynamic>> kMPAs = [
  {
    'id': 'hawar',
    'nameAr': 'محمية جزر حوار',
    'center': [25.6667, 50.7667],
    'radiusKm': 15.0,
  },
  {
    'id': 'tubli',
    'nameAr': 'محمية خليج توبلي',
    'center': [26.1667, 50.5667],
    'radiusKm': 3.5,
  },
  {
    'id': 'mashtan',
    'nameAr': 'محمية جزيرة مشتان',
    'center': [25.8833, 50.6500],
    'radiusKm': 2.0,
  },
  {
    'id': 'duwhat_arad',
    'nameAr': 'محمية ضوحة عراد',
    'center': [26.2500, 50.6500],
    'radiusKm': 1.5,
  },
  {
    'id': 'fasht_bulthama',
    'nameAr': 'محمية فشت بولتامة',
    'center': [26.4833, 50.4500],
    'radiusKm': 4.0,
  },
];

/// Confirmed fishing spots.
const List<Map<String, dynamic>> kConfirmedSpots = [
  {
    'id': 'FSJ001',
    'nameAr': 'فشت الجاريم',
    'nameEn': 'Fasht Al-Jarim',
    'lat': 26.4500,
    'lng': 50.5167,
    'zone': 'northern',
    'depth': 2.0,
    'bottomType': 'coral_reef',
    'species': ['hamour', 'safi', 'rubyan', 'sheum'],
    'confidence': 'high',
    'mpa': false,
  },
  {
    'id': 'FSA001',
    'nameAr': 'فشت الأعظم',
    'nameEn': 'Fasht Al-Azm',
    'lat': 25.9167,
    'lng': 50.6500,
    'zone': 'eastern',
    'depth': 5.0,
    'bottomType': 'seagrass_sandy',
    'species': ['rubyan', 'ghabgab', 'sheri'],
    'confidence': 'high',
    'mpa': false,
  },
  {
    'id': 'HAW001',
    'nameAr': 'جزر حوار',
    'nameEn': 'Hawar Islands',
    'lat': 25.6667,
    'lng': 50.7667,
    'zone': 'eastern',
    'depth': 8.0,
    'bottomType': 'seagrass',
    'species': ['hamour', 'rubyan', 'sheri'],
    'confidence': 'high',
    'mpa': true,
  },
  {
    'id': 'BUD001',
    'nameAr': 'البديع',
    'nameEn': 'Budaiya',
    'lat': 26.2000,
    'lng': 50.4300,
    'zone': 'western',
    'depth': 4.0,
    'bottomType': 'sandy',
    'species': ['hamour', 'safi', 'sheum'],
    'confidence': 'high',
    'mpa': false,
  },
  {
    'id': 'ZAL001',
    'nameAr': 'الزلاق',
    'nameEn': 'Zallaq',
    'lat': 26.0500,
    'lng': 50.4667,
    'zone': 'western',
    'depth': 5.0,
    'bottomType': 'sandy_rocky',
    'species': ['hamour', 'kanad', 'sheum'],
    'confidence': 'high',
    'mpa': false,
  },
  {
    'id': 'SIT001',
    'nameAr': 'جسر سترة',
    'nameEn': 'Sitra Bridge',
    'lat': 26.1333,
    'lng': 50.6167,
    'zone': 'eastern',
    'depth': 3.0,
    'bottomType': 'muddy',
    'species': ['safi', 'sheum', 'ghabgab'],
    'confidence': 'high',
    'mpa': false,
  },
  {
    'id': 'HID001',
    'nameAr': 'الحد',
    'nameEn': 'Hidd',
    'lat': 26.2167,
    'lng': 50.6667,
    'zone': 'eastern',
    'depth': 6.0,
    'bottomType': 'sandy',
    'species': ['hamour', 'sheri', 'rubyan'],
    'confidence': 'high',
    'mpa': false,
  },
  {
    'id': 'AMW001',
    'nameAr': 'جزر أمواج',
    'nameEn': 'Amwaj Islands',
    'lat': 26.2833,
    'lng': 50.6667,
    'zone': 'eastern',
    'depth': 7.0,
    'bottomType': 'sandy_reef',
    'species': ['hamour', 'kanad', 'sheri'],
    'confidence': 'high',
    'mpa': false,
  },
  {
    'id': 'UMN001',
    'nameAr': 'أم النعسان',
    'nameEn': 'Umm An Nasan',
    'lat': 26.1500,
    'lng': 50.3833,
    'zone': 'western',
    'depth': 10.0,
    'bottomType': 'rocky_reef',
    'species': ['hamour', 'kanad', 'zebaidi'],
    'confidence': 'medium',
    'mpa': false,
  },
  {
    'id': 'FSB001',
    'nameAr': 'فشت بولتامة',
    'nameEn': 'Fasht Bulthama',
    'lat': 26.4833,
    'lng': 50.4500,
    'zone': 'northern',
    'depth': 3.0,
    'bottomType': 'coral',
    'species': ['hamour', 'sheri'],
    'confidence': 'high',
    'mpa': true,
  },
];
